version: '3.4'

services:
  coze-discord-proxy:
    image: zorro1133/coze-discord-proxy:latest
    container_name: coze-discord-proxy
    restart: always
    ports:
      - "7077:7077"
    volumes:
      - ./data:/app/coze-discord-proxy/data
    environment:
      - BOT_TOKEN=MTIwOTQwNzM5MjU0NzM0ODQ4MA.GdqXxq.N2FWVmRB7J04ajJOkB_Ii404pCigiDjZ9jQdvs
      - GUILD_ID=1209399967563784252
      - COZE_BOT_ID=1209401091121479701
      - CHANNEL_ID=1209399967563784255
      - PROXY_SECRET=123456
      - TZ=Asia/Shanghai
